config:
  seed: 2357
  phase: 'test'
  batch_size: 128
  model: 'simple_transformer'
  data_path: './data/train_data.csv'
  weights_path: './weights/20201208/best.pth'
  max_sent_len: 512
  out_dir: './out'

model:
  bilstm:
    embedding_dim: 300
    hidden_size: 150
    grad_clip_th: 100
    fasttext_weights: './weights/fasttext/wiki-news-300d-1M.vec'

  simple_transformer:
    embedding_dim: 300
    d_model: 300
    fasttext_weights: './weights/fasttext/wiki-news-300d-1M.vec'
