config:
  seed: 2357
  phase: 'train'
  epochs: 100
  batch_size: 64
  learning_rate: 0.01
  model: 'bilstm'
  data_path: './data/augmented_train_data.csv'
  max_sent_len: 512
  valid_size: 0.1
  save_dir: './weights'
  log_dir: './logs'

model:
  bilstm:
    embedding_dim: 300
    hidden_size: 150
    fasttext_weights: './weights/fasttext/wiki-news-300d-1M.vec'

  simple_transformer:
    embedding_dim: 300
    d_model: 300
    fasttext_weights: './weights/fasttext/wiki-news-300d-1M.vec'
